# for year in election_data.keys():
#     print("Year", year)
#     print("------------")
#     visited = []
#     for c in election_data[year].keys():
#         print("\tConstituency", c)
#         for party in election_data[year][c]:
#             if party.votes > 1000 and party.name not in visited:
#                 visited.append(party.name)
#                 print("\t\t-", party.name)


# for year in election_data.keys():
#     print("Year", year)
#     print("------------")
#     visited = []
#     for c in election_data[year].keys():
#         print("\tConstituency", c)
#         for party in election_data[year][c]:
#             if party.votes > 1000 and party.name not in visited:
#                 visited.append(party.name)
#                 print("\t\t-", party.name)


parties_mapping = {
    2007: {
        "HRVATSKA SOCIJALNO LIBERALNA STRANKA - HSLS, HRVATSKA SELJAČKA STRANKA - HSS, Nositelj liste: STANKO ZRILIĆ": "HSS",
        "SOCIJALDEMOKRATSKA PARTIJA HRVATSKE - SDP, Nositelj liste: ZORAN MILANOVIĆ": "SDP",
        "HRVATSKA SELJAČKA STRANKA - HSS, HRVATSKA SOCIJALNO LIBERALNA STRANKA - HSLS, PRIMORSKO GORANSKI SAVEZ - PGS, Nositelj liste: BOŽIDAR PANKRETIĆ": "HSS",
        "HRVATSKA STRANKA PRAVA - HSP, Nositelj liste: ANTO ĐAPIĆ": "HSP",
        "HRVATSKA DEMOKRATSKA ZAJEDNICA - HDZ, Nositelj liste: dr.sc. IVO SANADER                                 ": "HDZ",
        "HRVATSKA SELJAČKA STRANKA - HSS, HRVATSKA SOCIJALNO LIBERALNA STRANKA - HSLS, Nositelj liste: MARIJANA PETIR": "HSS",
        "HRVATSKA SOCIJALNO LIBERALNA STRANKA - HSLS, HRVATSKA SELJAČKA STRANKA - HSS, ZAGORSKA DEMOKRATSKA STRANKA - ZDS, Nositelj liste: dr.sc. IVAN ČEHOK": "HSS",
        "HRVATSKA SELJAČKA STRANKA - HSS, HRVATSKA SOCIJALNO LIBERALNA STRANKA - HSLS, ZAGORSKA STRANKA - ZS, ZAGORSKA DEMOKRATSKA STRANKA - ZDS, Nositelj liste: TATJANA HOLJEVAC": "HSS",
        "Kandidat: RATKO GAJICA, Zamjenik: JOVAN AJDUKOVIĆ, Predlagatelj: SAMOSTALNA DEMOKRATSKA SRPSKA STRANKA - SDSS                                       ": "SDSS",
        "HRVATSKI DEMOKRATSKI SAVEZ SLAVONIJE I BARANJE - HDSSB, Nositelj liste: BRANIMIR GLAVAŠ, dipl.iur.                                        ": "HDSSB",
        "SOCIJALDEMOKRATSKA PARTIJA HRVATSKE - SDP, Nositelj liste: ZORAN MILANOVIĆ                                 ": "SDP",
        "Kandidat: dr.sc. MILORAD PUPOVAC, Zamjenik: ALEKSANDAR MILOŠEVIĆ, Predlagatelj: SAMOSTALNA DEMOKRATSKA SRPSKA STRANKA - SDSS                                       ": "SDSS",
        "PRIMORSKO GORANSKI SAVEZ - PGS, HRVATSKA SELJAČKA STRANKA - HSS, HRVATSKA SOCIJALNO LIBERALNA STRANKA - HSLS, Nositelj liste: NIKOLA IVANIŠ": "HSS",
        "HRVATSKA SELJAČKA STRANKA - HSS, HRVATSKA SOCIJALNO LIBERALNA STRANKA - HSLS, Nositelj liste: STIPO GABRIĆ": "HSS",
        "Kandidat: VOJISLAV STANIMIROVIĆ, dr.med., Zamjenik: MILE HORVAT, Predlagatelj: SAMOSTALNA DEMOKRATSKA SRPSKA STRANKA - SDSS                                       ": "SDSS",
        "HRVATSKA SELJAČKA STRANKA - HSS, HRVATSKA SOCIJALNO LIBERALNA STRANKA - HSLS, Nositelj liste: JOSIP FRIŠČIĆ": "HSS",
        "SAMOSTALNA DEMOKRATSKA SRPSKA STRANKA - SDSS, Nositelj liste: dr.sc. MILORAD PUPOVAC": "SDSS",
        "HRVATSKI DEMOKRATSKI SAVEZ SLAVONIJE I BARANJE - HDSSB, Nositelj liste: BRANIMIR GLAVAŠ, dipl.iur.                    ": "HDSSB",
        "HRVATSKA SELJAČKA STRANKA - HSS, HRVATSKA SOCIJALNO LIBERALNA STRANKA - HSLS, Nositelj liste: ZDRAVKO KELIĆ": "HSS",
        "HRVATSKA SELJAČKA STRANKA - HSS, HRVATSKA SOCIJALNO LIBERALNA STRANKA - HSLS, Nositelj liste: ŽELJKO PECEK": "HSS",
        "STRANKA UMIROVLJENIKA - SU, Nositelj liste: VENKO BANOVIĆ": "SU",
        "ZELENA STRANKA - ZS, AKCIJA SOCIJALDEMOKRATA HRVATSKE - ASH, HRVATSKA RADNIČKA STRANKA - HRS, JADRANSKA SOCIJALDEMOKRATSKA STRANKA HRVATSKE - JADRANSKI SOCIJALDEMOKRATI, Nositelj liste: ALJOŠA BABIĆ ": "ZS",
        "STRANKA UMIROVLJENIKA - SU, Nositelj liste: JOSIP ŠUNIĆ": "SU",
        "HRVATSKA NARODNA STRANKA-LIBERALNI DEMOKRATI - HNS, Nositelj liste: RADIMIR ČAČIĆ                   ": "HNS",
        "STRANKA UMIROVLJENIKA - SU, Nositelj liste: JOSIP ŽUŽUL": "SU",
        "STRANKA UMIROVLJENIKA - SU, Nositelj liste: BORIS NIKOLIĆ-MALORA": "SU",
        "STRANKA UMIROVLJENIKA - SU, Nositelj liste: MIROSLAV SLAVIĆ": "SU",
        "STRANKA UMIROVLJENIKA - SU, Nositelj liste: STANISLAV JELAČA": "SU",
        "HRVATSKA NARODNA STRANKA-LIBERALNI DEMOKRATI - HNS, Nositelj liste: dr.sc. VESNA PUSIĆ                    ": "HNS",
        "HRVATSKA NARODNA STRANKA-LIBERALNI DEMOKRATI - HNS, Nositelj liste: RADIMIR ČAČIĆ                    ": "HNS",
        "HRVATSKA NARODNA STRANKA-LIBERALNI DEMOKRATI - HNS, Nositelj liste: dr.sc. RADIMIR ČAČIĆ                    ": "HNS",
        "ISTARSKI DEMOKRATSKI SABOR - IDS, Nositelj liste: DAMIR KAJIN                    ": "IDS",
        "Kandidat: BAJRO BAJRIĆ, Predlagatelj: HRVATSKA SOCIJALNO-LIBERALNA STRANKA - HSLS ": "HSLS",
        "HRVATSKI DEMOKRATSKI SAVEZ SLAVONIJE I BARANJE - HDSSB  , Nositelj liste:  prof.dr.sc. VLADIMIR ŠIŠLJAGIĆ  ": "HDSSB",
        "HRVATSKA STRANKA PRAVA - HSP , \"HRVATSKA STRAŽA\" NACIONALNA STRANKA - HS NS  , Nositelj liste:  DANIEL SRB   ": "HSP",
        "HRVATSKI DEMOKRATSKI SAVEZ SLAVONIJE I BARANJE - HDSSB  , Nositelj liste:  prof.dr.sc. VLADIMIR ŠIŠLJAGIĆ": "HDSSB",
        "HRVATSKI DEMOKRATSKI SAVEZ SLAVONIJE I BARANJE - HDSSB": "HDSSB",
        "HRVATSKA STRANKA PRAVA DR.ANTE STARČEVIĆ - HSP DR.ANTE STARČEVIĆ , HRVATSKA ČISTA STRANKA PRAVA - HČSP  , Nositelj liste:  RUŽA TOMAŠIĆ": "HSP"
    },
    2011: {
        "SAVEZ ZA PROMJENE - SP, AUTOHTONA - HRVATSKA SELJAČKA STRANKA - A-HSS, Nositelj liste: IVAN PERNAR ": "A-HSS",
        "SOCIJALDEMOKRATSKA PARTIJA HRVATSKE - SDP, HRVATSKA NARODNA STRANKA - LIBERALNI DEMOKRATI - HNS, ISTARSKI DEMOKRATSKI SABOR - IDS, HRVATSKA STRANKA UMIROVLJENIKA - HSU, Nositelj liste: ZORAN MILANOVIĆ": "SDP",
        "HRVATSKA DEMOKRATSKA ZAJEDNICA - HDZ, Nositelj liste: JADRANKA KOSOR \xa0": "HDZ",
        "HRVATSKI LABURISTI-STRANKA RADA, Nositelj liste: DRAGUTIN LESAR \xa0": "LABURISTI",
        "HRVATSKA SOCIJALNO-LIBERALNA STRANKA - HSLS, Nositelj liste: prof.dr.sc. VELIMIR SRIĆA \xa0": "HSLS",
        "BLOK UMIROVLJENICI ZAJEDNO - BUZ, PRIMORSKO GORANSKI SAVEZ - PGS, HRVATSKA RADNIČKA STRANKA - HRS, Nositelj liste: prof.dr.sc. LJUBO JURČIĆ ": "BUZ",
        "HRVATSKA STRANKA PRAVA - HSP, Nositelj liste: ANTE PRKAČIN \xa0": "HSP",
        "HRVATSKA STRANKA PRAVA DR.ANTE STARČEVIĆ - HSP DR.ANTE STARČEVIĆ, HRVATSKA ČISTA STRANKA PRAVA - HČSP, Nositelj liste: RUŽA TOMAŠIĆ": "HSP",
        "HRVATSKI RAST - HRAST, Nositelj liste: KREŠIMIR MILETIĆ ": "HRAST",
        "HRVATSKA SELJAČKA STRANKA - HSS, ZELENA STRANKA - ZS, STRANKA PENZIONERA - SP, Nositelj liste: DARKO VULETIĆ ": "HSS",
        "HRVATSKA DEMOKRŠĆANSKA STRANKA - HDS  , Nositelj liste:  prof.dr.sc. JOSIP JURČEVIĆ ": "HDS",
        "SAMOSTALNA DEMOKRATSKA SRPSKA STRANKA - SDSS  , Nositelj liste:  prof.dr.sc. SLOBODAN UZELAC ": "SDSS",
        "HRVATSKA SELJAČKA STRANKA - HSS  , Nositelj liste:  JOSIP FRIŠČIĆ": "HSS",
        "BLOK UMIROVLJENICI ZAJEDNO - BUZ , PRIMORSKO GORANSKI SAVEZ - PGS , HRVATSKA RADNIČKA STRANKA - HRS  , Nositelj liste:  prof.dr.sc. LJUBO JURČIĆ   ": "BUZ",
        "HRVATSKA SELJAČKA STRANKA - HSS , ZELENA STRANKA - ZS , STRANKA PENZIONERA - SP  , Nositelj liste:  mr.sc. STIPO GABRIĆ": "HSS",
        "HRVATSKA SELJAČKA STRANKA - HSS  , Nositelj liste:  MARIJANA PETIR ": "HSS",
        "HRVATSKA STRANKA PRAVA - HSP  , Nositelj liste:  MIRKO DUSPARA ": "HSP",
        "HRVATSKA DEMOKRATSKA ZAJEDNICA - HDZ  , Nositelj liste:  JADRANKA KOSOR": "HDZ",
        "SOCIJALDEMOKRATSKA PARTIJA HRVATSKE - SDP , HRVATSKA NARODNA STRANKA - LIBERALNI DEMOKRATI - HNS , ISTARSKI DEMOKRATSKI SABOR - IDS , HRVATSKA STRANKA UMIROVLJENIKA - HSU  , Nositelj liste:  ZORAN MILANOVIĆ  ": "SDP",
        "HRVATSKA DEMOKRŠĆANSKA STRANKA - HDS , JEDINO HRVATSKA - POKRET ZA HRVATSKU - JEDINO HRVATSKA  , Nositelj liste:  prof.dr.sc. JOSIP JURČEVIĆ": "HDS",
        "Kandidat: prof.dr.sc. MILORAD PUPOVAC , Zamjenik: ALEKSANDAR MILOŠEVIĆ, dipl.pol. , Predlagatelj: SAMOSTALNA DEMOKRATSKA SRPSKA STRANKA - SDSS ": "SDSS",
        "HRVATSKA STRANKA PRAVA DR.ANTE STARČEVIĆ - HSP DR.ANTE STARČEVIĆ , HRVATSKA ČISTA STRANKA PRAVA - HČSP  , Nositelj liste:  RUŽA TOMAŠIĆ ": "HSP",
        "HRVATSKA SOCIJALNO-LIBERALNA STRANKA - HSLS  , Nositelj liste:  DARINKO KOSOR ": "HSLS",
        "HRVATSKA DEMOKRATSKA ZAJEDNICA - HDZ , HRVATSKA GRAĐANSKA STRANKA - HGS  , Nositelj liste:  JADRANKA KOSOR": "HDZ",
        "HRVATSKI RAST - HRAST  , Nositelj liste:  VEDRAN UJEVIĆ": "HRAST",
        "AKCIJA MLADIH - AM , LISTA ZA RIJEKU - LISTA-RI , STRANKA UMIROVLJENIKA HRVATSKE-BLOK UMIROVLJENICI ZAJEDNO - SUH  , Nositelj liste:  DANKO ŠVORINIĆ ": "AM",
        "HRVATSKA SOCIJALNO-LIBERALNA STRANKA - HSLS  , Nositelj liste:  DARINKO KOSOR": "HSLS",
        "BLOK UMIROVLJENICI ZAJEDNO - BUZ , PRIMORSKO GORANSKI SAVEZ - PGS , HRVATSKA RADNIČKA STRANKA - HRS  , Nositelj liste:  prof.dr.sc. LJUBO JURČIĆ ": "BUZ",
        "HRVATSKA SOCIJALNO-LIBERALNA STRANKA - HSLS  , Nositelj liste:  DARINKO KOSOR  ": "HSLS",
        "HRVATSKA STRANKA PRAVA - HSP  , Nositelj liste:  ANTO ĐAPIĆ  ": "HSP",
        "SOCIJALDEMOKRATSKA PARTIJA HRVATSKE - SDP , HRVATSKA NARODNA STRANKA - LIBERALNI DEMOKRATI - HNS , ISTARSKI DEMOKRATSKI SABOR - IDS , HRVATSKA STRANKA UMIROVLJENIKA - HSU  , Nositelj liste:  RADIMIR ČAČIĆ": "SDP",
        "HRVATSKI RAST - HRAST  , Nositelj liste:  JELENA ĆORIĆ MUDROVČIĆ  ": "HRAST",
        "HRVATSKA STRANKA PRAVA - HSP  , Nositelj liste:  DANIEL SRB ": "HSP",
        "HRVATSKA SELJAČKA STRANKA - HSS , ZELENA STRANKA - ZS , STRANKA PENZIONERA - SP  , Nositelj liste:  mr.sc. BOŽIDAR PANKRETIĆ  ": "HSS",
        "HRVATSKI LABURISTI-STRANKA RADA  , Nositelj liste:  DRAGUTIN LESAR": "LABURISTI",
        "HRVATSKA DEMOKRATSKA ZAJEDNICA - HDZ  , Nositelj liste:  JADRANKA KOSOR ": "HDZ",
        "HRVATSKA DEMOKRATSKA ZAJEDNICA - HDZ , DEMOKRATSKI CENTAR - DC  , Nositelj liste:  JADRANKA KOSOR ": "HDZ",
        "HRVATSKA SOCIJALNO-LIBERALNA STRANKA - HSLS  , Nositelj liste:  DRAŽEN BUDIŠA  ": "HSLS",
        "SOCIJALDEMOKRATSKA PARTIJA HRVATSKE - SDP , HRVATSKA NARODNA STRANKA - LIBERALNI DEMOKRATI - HNS , ISTARSKI DEMOKRATSKI SABOR - IDS , HRVATSKA STRANKA UMIROVLJENIKA - HSU  , Nositelj liste:  ZORAN MILANOVIĆ ": "SDP",
        "AUTOHTONA - HRVATSKA SELJAČKA STRANKA - A-HSS , SAVEZ ZA PROMJENE - SP  , Nositelj liste:  BRANKO BORKOVIĆ": "A-HSP",
        "HRVATSKA SELJAČKA STRANKA - HSS  , Nositelj liste:  ZORAN SMOLIĆ": "HSS",
        "HRVATSKI RAST - HRAST  , Nositelj liste:  ZVONKO BAJAN  ": "HRAST",
        "HRVATSKI RAST - HRAST  , Nositelj liste:  ZDRAVKO ROŠKO": "HRAST",
        "HRVATSKA SELJAČKA STRANKA - HSS  , Nositelj liste:  DAVOR VLAOVIĆ, dipl.ing. ": "HSS",
        "HRVATSKI RAST - HRAST  , Nositelj liste:  LADISLAV ILČIĆ  ": "HRAST",
        "SOCIJALDEMOKRATSKA PARTIJA HRVATSKE - SDP , HRVATSKA NARODNA STRANKA - LIBERALNI DEMOKRATI - HNS , ISTARSKI DEMOKRATSKI SABOR - IDS , HRVATSKA STRANKA UMIROVLJENIKA - HSU  , Nositelj liste:  ZORAN MILANOVIĆ": "SDP",
        "HRVATSKA DEMOKRATSKA ZAJEDNICA - HDZ , HRVATSKA GRAĐANSKA STRANKA - HGS  , Nositelj liste:  JADRANKA KOSOR ": "HDZ",
        "HRVATSKA STRANKA PRAVA - HSP  , Nositelj liste:  DANIEL SRB": "HSP",
        "HRVATSKI DEMOKRATSKI SAVEZ SLAVONIJE I BARANJE - HDSSB": "HDSSB",
        "HRVATSKA STRANKA PRAVA DR.ANTE STARČEVIĆ - HSP DR.ANTE STARČEVIĆ , HRVATSKA ČISTA STRANKA PRAVA - HČSP  , Nositelj liste:  RUŽA TOMAŠIĆ  ": "HSP",
        "HRVATSKA DEMOKRŠĆANSKA STRANKA - HDS , JEDINO HRVATSKA - POKRET ZA HRVATSKU - JEDINO HRVATSKA  , Nositelj liste:  prof.dr.sc. JOSIP JURČEVIĆ ": "HDS",
        "Kandidat: PAŠK KAČINARI, Predlagatelj: , SAVEZ ZA PROMJENE - SP , AUTOHTONA - HRVATSKA SELJAČKA STRANKA - A-HSS ": "A-HSS",
        "HRVATSKI DEMOKRATSKI SAVEZ SLAVONIJE I BARANJE - HDSSB  , Nositelj liste:  prof.dr.sc. VLADIMIR ŠIŠLJAGIĆ  ": "HDSSB",
        "HRVATSKI DEMOKRATSKI SAVEZ SLAVONIJE I BARANJE - HDSSB  , Nositelj liste:  prof.dr.sc. VLADIMIR ŠIŠLJAGIĆ": "HDSSB"
    },
    2015: {
        "SOCIJALDEMOKRATSKA PARTIJA HRVATSKE - SDP, HRVATSKA NARODNA STRANKA - LIBERALNI DEMOKRATI - HNS, HRVATSKA STRANKA UMIROVLJENIKA - HSU, HRVATSKI LABURISTI - STRANKA RADA, AUTOHTONA - HRVATSKA SELJAČKA STRANKA - A - HSS, ZAGORSKA STRANKA - ZS": "SDP",
        "HRVATSKA DEMOKRATSKA ZAJEDNICA - HDZ, HRVATSKA SELJAČKA STRANKA - HSS, HRVATSKA STRANKA PRAVA DR. ANTE STARČEVIĆ - HSP AS, BLOK UMIROVLJENICI ZAJEDNO - BUZ, HRVATSKA SOCIJALNO - LIBERALNA STRANKA - HSLS, HRAST - POKRET ZA USPJEŠNU HRVATSKU, HRVATSKA DEMOKRŠĆANSKA STRANKA - HDS, ZAGORSKA DEMOKRATSKA STRANKA - ZDS": "HDZ",
        "MOST NEZAVISNIH LISTA - MOST": "MOST",
        '"BANDIĆ MILAN 365 - STRANKA RADA I SOLIDARNOSTI", DEMOKRATSKA PRIGORSKO - ZAGREBAČKA STRANKA - DPS, DEMOKRATSKA STRANKA ŽENA - DSŽ, HRVATSKA EUROPSKA STRANKA - HES, HRVATSKA RADNIČKA STRANKA - HRS, HRVATSKA STRANKA ZELENIH - EKO SAVEZ - ZELENI, ISTARSKI DEMOKRATI - DEMOCRATICI ISTRIANI - ID - DI, MEĐIMURSKA STRANKA - MS, NEZAVISNI SELJACI HRVATSKE - NSH, NOVI VAL - STRANKA RAZVOJA - NOVI VAL, STRANKA UMIROVLJENIKA - SU, UMIROVLJENIČKA DEMOKRATSKA UNIJA - UDU, ZELENI SAVEZ - ZELENI, ZELENA STRANKA - ZS': "STRANKA RADA I SOLIDARNOSTI",
        "ODRŽIVI RAZVOJ HRVATSKE - ORaH": "ORaH",
        "U IME OBITELJI - PROJEKT DOMOVINA": "PROJEKT DOMOVINA",
        "NAPRIJED HRVATSKA! - PROGRESIVNI SAVEZ IVE JOSIPOVIĆA, NARODNA STRANKA - REFORMISTI - REFORMISTI, STRANKA HRVATSKIH UMIROVLJENIKA - UMIROVLJENICI, ZELENI FORUM, DUBROVAČKI DEMOKRATSKI SABOR - DDS": "NAPRIJED HRVATSKA!, REFORMISTI",
        "NARODNA STRANKA - REFORMISTI - REFORMISTI, NAPRIJED HRVATSKA! - PROGRESIVNI SAVEZ IVE JOSIPOVIĆA, STRANKA HRVATSKIH UMIROVLJENIKA - UMIROVLJENICI, ZELENI FORUM, DUBROVAČKI DEMOKRATSKI SABOR - DDS": "NAPRIJED HRVATSKA!, REFORMISTI",
        "AUTOHTONA - HRVATSKA STRANKA PRAVA - A - HSP": "A-HSP",
        "HRVATSKI DEMOKRATSKI SAVEZ SLAVONIJE I BARANJE - HDSSB": "HDSSB",
        "DEMOKRATSKI SAVEZ NACIONALNE OBNOVE - DESNO": "DESNO",
        "HRVATSKA KONZERVATIVNA STRANKA - HKS, HRVATSKA STRANKA PRAVA - HSP, OBITELJSKA STRANKA - OS": "HKS, HSP",
        "ISTARSKI DEMOKRATSKI SABOR - IDS, PRIMORSKO GORANSKI SAVEZ - PGS, LISTA ZA RIJEKU - RI": "IDS",
        'BANDIĆ MILAN 365 - STRANKA RADA I SOLIDARNOSTI", ISTARSKI DEMOKRATI - DEMOCRATICI ISTRIANI - ID - DI, DEMOKRATSKA PRIGORSKO - ZAGREBAČKA STRANKA - DPS, DEMOKRATSKA STRANKA ŽENA - DSŽ, HRVATSKA EUROPSKA STRANKA - HES, HRVATSKA RADNIČKA STRANKA - HRS, HRVATSKA STRANKA ZELENIH - EKO SAVEZ - ZELENI, MEĐIMURSKA STRANKA - MS, NEZAVISNI SELJACI HRVATSKE - NSH, NOVI VAL - STRANKA RAZVOJA - NOVI VAL, STRANKA UMIROVLJENIKA - SU, UMIROVLJENIČKA DEMOKRATSKA UNIJA - UDU, ZELENI SAVEZ - ZELENI, ZELENA STRANKA - ZS': "STRANKA RADA I SOLIDARNOSTI",
        "AKCIJA MLADIH - AM": "AM",
        "SOCIJALDEMOKRATSKA PARTIJA HRVATSKE - SDP, HRVATSKA NARODNA STRANKA - LIBERALNI DEMOKRATI - HNS, HRVATSKA STRANKA UMIROVLJENIKA - HSU, HRVATSKI LABURISTI - STRANKA RADA, AUTOHTONA - HRVATSKA SELJAČKA STRANKA - A - HSS, ZAGORSKA STRANKA - ZS, SAMOSTALNA DEMOKRATSKA SRPSKA STRANKA - SDSS": "SDP",
        "ŽIVI ZID, AKCIJA MLADIH - AM": "ŽIVI ZID",
        "HRVATSKA ZORA STRANKA NARODA - HZ": "HZ",
        "HRVATSKA DEMOKRATSKA ZAJEDNICA - HDZ, HRVATSKA SELJAČKA STRANKA - HSS, HRVATSKA STRANKA PRAVA DR. ANTE STARČEVIĆ - HSP AS, BLOK UMIROVLJENICI ZAJEDNO - BUZ, HRVATSKA SOCIJALNO - LIBERALNA STRANKA - HSLS, HRVATSKA DEMOKRŠĆANSKA STRANKA - HDS, ZAGORSKA DEMOKRATSKA STRANKA - ZDS, HRAST - POKRET ZA USPJEŠNU HRVATSKU": "HDZ",
        "NARODNA STRANKA - REFORMISTI - REFORMISTI, DUBROVAČKI DEMOKRATSKI SABOR - DDS, NAPRIJED HRVATSKA! - PROGRESIVNI SAVEZ IVE JOSIPOVIĆA, STRANKA HRVATSKIH UMIROVLJENIKA - UMIROVLJENICI, ZELENI FORUM": "NAPRIJED HRVATSKA!, REFORMISTI",
        "BRANITELJSKO DOMOLJUBNA STRANKA HRVATSKE - BDSH, HRVATSKA BRANITELJSKA PUČKA STRANKA - HBPS": "HBPS",
        "BRANITELJSKO DOMOLJUBNA STRANKA HRVATSKE - BDSH": "BDSH",
        '"BANDIĆ MILAN 365 - STRANKA RADA I SOLIDARNOSTI", ISTARSKI DEMOKRATI - DEMOCRATICI ISTRIANI - ID - DI, DEMOKRATSKA PRIGORSKO - ZAGREBAČKA STRANKA - DPS, DEMOKRATSKA STRANKA ŽENA - DSŽ, HRVATSKA EUROPSKA STRANKA - HES, HRVATSKA RADNIČKA STRANKA - HRS, HRVATSKA STRANKA ZELENIH - EKO SAVEZ - ZELENI, MEĐIMURSKA STRANKA - MS, NEZAVISNI SELJACI HRVATSKE - NSH, NOVI VAL - STRANKA RAZVOJA - NOVI VAL, STRANKA UMIROVLJENIKA - SU, UMIROVLJENIČKA DEMOKRATSKA UNIJA - UDU, ZELENI SAVEZ - ZELENI, ZELENA STRANKA - ZS': "STRANKA RADA I SOLIDARNOSTI"
    },
    2016: {
        "SOCIJALDEMOKRATSKA PARTIJA HRVATSKE - SDP, HRVATSKA NARODNA STRANKA - LIBERALNI DEMOKRATI - HNS, HRVATSKA SELJAČKA STRANKA - HSS, HRVATSKA STRANKA UMIROVLJENIKA - HSU": "SDP",
        "HRVATSKA DEMOKRATSKA ZAJEDNICA - HDZ, HRVATSKA SOCIJALNO - LIBERALNA STRANKA - HSLS": "HDZ",
        "MOST NEZAVISNIH LISTA - MOST": "MOST",
        "ŽIVI ZID, PROMIJENIMO HRVATSKU, AKCIJA MLADIH, ABECEDA DEMOKRACIJE": "ŽIVI ZID",
        "PAMETNO, ZA GRAD": "PAMETNO",
        '"BANDIĆ MILAN 365 - STRANKA RADA I SOLIDARNOSTI" - "STRANKA RADA I SOLIDARNOSTI", NARODNA STRANKA - REFORMISTI - REFORMISTI, NOVI VAL - STRANKA RAZVOJA - NOVI VAL, HRVATSKA SELJAČKA STRANKA - STJEPAN RADIĆ - HSS - SR, BLOK UMIROVLJENICI ZAJEDNO - BUZ': "STRANKA RADA I SOLIDARNOSTI",
        "SASVIM MALA STRANKA - SMS": "SMS",
        "ŽIVI ZID, PROMIJENIMO HRVATSKU, AKCIJA MLADIH, HRVATSKA DEMOKRATSKA SELJAČKA STRANKA, ABECEDA DEMOKRACIJE": "ŽIVI ZID",
        "STRANKA UMIROVLJENIKA - SU": "SU",
        "HRVATSKA STRANKA PRAVA - HSP, HRVATSKA ČISTA STRANKA PRAVA - HČSP, AKCIJA ZA BOLJU HRVATSKU - ABH, OBITELJSKA STRANKA - OS": "HSP",
        "HRVATSKA DEMOKRATSKA ZAJEDNICA - HDZ": "HDZ",
        "ŽIVI ZID, PROMIJENIMO HRVATSKU, AKCIJA MLADIH, ABECEDA DEMOKRACIJE, HRVATSKA DEMOKRATSKA SELJAČKA STRANKA, MEĐIMURSKA STRANKA": "ŽIVI ZID",
        "NEZAVISNA LISTA STIPE PETRINA - NLSP, SLOBODNA HRVATSKA - SH, POKRET ZAJEDNO, ODRŽIVI RAZVOJ HRVATSKE - ORaH": "ORaH",
        "HRVATSKI LABURISTI - STRANKA RADA - LABURISTI": "LABURISTI",
        "HRVATSKI DEMOKRATSKI SAVEZ SLAVONIJE I BARANJE - HDSSB, HRVATSKA KONZERVATIVNA STRANKA - HKS": "HDSSB",
        "HRVATSKI DEMOKRATSKI SAVEZ SLAVONIJE I BARANJE - HDSSB": "HDSSB",
        "HRVATSKA STRANKA PRAVA DR. ANTE STARČEVIĆ - HSP AS, DEMOKRATSKI SAVEZ NACIONALNE OBNOVE - DESNO, HRVATSKA KRŠĆANSKA DEMOKRATSKA UNIJA - DR. MARKO VESELICA - HKDU - DR. MARKO VESELICA, HRVATSKA DEMOKRATSKA STRANKA - HDS, UJEDINJENA STRANKA PRAVA - USP": "HSP",
        "ŽIVI ZID, PROMIJENIMO HRVATSKU, AKCIJA MLADIH": "ŽIVI ZID",
        "HRVATSKA STRANKA PRAVA DR. ANTE STARČEVIĆ - HSP AS, DEMOKRATSKI SAVEZ NACIONALNE OBNOVE - DESNO, HRVATSKA KRŠĆANSKA DEMOKRATSKA UNIJA - DR. MARKO VESELICA - HKDU - DR. MARKO VESELICA, UJEDINJENA STRANKA PRAVA - USP, HRVATSKA DEMOKRATSKA STRANKA - HDS": "HSP",
        "HRVATSKA STRANKA PRAVA DR. ANTE STARČEVIĆ - HSP AS, HRVATSKA KRŠĆANSKA DEMOKRATSKA UNIJA - DR. MARKO VESELICA - HKDU - DR. MARKO ": "HSP",
        "PRIMORSKO GORANSKI SAVEZ - PGS, ISTARSKI DEMOKRATSKI SABOR - IDS, LISTA ZA RIJEKU - RI": "IDS",
        "ISTARSKI DEMOKRATSKI SABOR - IDS, PRIMORSKO GORANSKI SAVEZ - PGS, LISTA ZA RIJEKU - RI": "IDS",
        "ISTARSKI DEMOKRATI - DEMOCRATICI ISTRIANI - ID - DI": "ID",
        "NEZAVISNA LISTA STIPE PETRINA - NLSP, SLOBODNA HRVATSKA - SH, POKRET ZAJEDNO, ODRŽIVI RAZVOJ HRVATSKE - ORaH, STRANKA HRVATSKOG ZAJEDNIŠTVA - SHZ, STRANKA UMIROVLJENIKA - SU": "ORaH",
        "HRVATSKA DEMOKRATSKA ZAJEDNICA - HDZ, HRVATSKA DEMOKRŠĆANSKA STRANKA - HDS": "HDZ",
        "EZAVISNA LISTA STIPE PETRINA - NLSP, SLOBODNA HRVATSKA - SH, POKRET ZAJEDNO, ODRŽIVI RAZVOJ HRVATSKE - ORaH, STRANKA UMIROVLJENIKA - SU": "ORaH",
        "BRANITELJSKO DOMOLJUBNA STRANKA HRVATSKE - BDSH, HRVATSKA BRANITELJSKA PUČKA STRANKA - HBPS": "HBPS",
        "BRANITELJSKO DOMOLJUBNA STRANKA HRVATSKE - BDSH": "BDSH",
        "AUTOHTONA - HRVATSKA STRANKA PRAVA - A - HSP": "A-HSP",
        '"BANDIĆ MILAN 365 - STRANKA RADA I SOLIDARNOSTI", ISTARSKI DEMOKRATI - DEMOCRATICI ISTRIANI - ID - DI, DEMOKRATSKA PRIGORSKO - ZAGREBAČKA STRANKA - DPS, DEMOKRATSKA STRANKA ŽENA - DSŽ, HRVATSKA EUROPSKA STRANKA - HES, HRVATSKA RADNIČKA STRANKA - HRS, HRVATSKA STRANKA ZELENIH - EKO SAVEZ - ZELENI, MEĐIMURSKA STRANKA - MS, NEZAVISNI SELJACI HRVATSKE - NSH, NOVI VAL - STRANKA RAZVOJA - NOVI VAL, STRANKA UMIROVLJENIKA - SU, UMIROVLJENIČKA DEMOKRATSKA UNIJA - UDU, ZELENI SAVEZ - ZELENI, ZELENA STRANKA - ZS': "STRANKA RADA I SOLIDARNOSTI"
    },
    2020: {
        "HRVATSKA DEMOKRATSKA ZAJEDNICA - HDZ, HRVATSKA SOCIJALNO - LIBERALNA STRANKA - HSLS": "HDZ",
        "SOCIJALDEMOKRATSKA PARTIJA HRVATSKE - SDP, HRVATSKA SELJAČKA STRANKA - HSS, HRVATSKA STRANKA UMIROVLJENIKA - HSU, SNAGA - STRANKA NARODNOG I GRAĐANSKOG AKTIVIZMA - SNAGA, GRAĐANSKO-LIBERALNI SAVEZ - GLAS, ISTARSKI DEMOKRATSKI SABOR - IDS, PRIMORSKO GORANSKI SAVEZ - PGS": "SDP",
        "MOŽEMO! - POLITIČKA PLATFORMA, ZAGREB JE NAŠ!, NOVA LJEVICA - NL, RADNIČKA FRONTA - RF, ODRŽIVI RAZVOJ HRVATSKE - ORAH, ZA GRAD": "MOŽEMO!",
        "DOMOVINSKI POKRET MIROSLAVA ŠKORE - DOMOVINSKI POKRET, HRVATSKI SUVERENISTI, BLOK ZA HRVATSKU - BLOK, HRVATSKA KONZERVATIVNA STRANKA - HKS, HRAST - POKRET ZA USPJEŠNU HRVATSKU, STRANKA UMIROVLJENIKA - SU, ZELENA LISTA": "DOMOVINSKI POKRET",
        "MOST NEZAVISNIH LISTA - MOST": "MOST",
        "STRANKA S IMENOM I PREZIMENOM, PAMETNO, FOKUS": "PAMETNO",
        "ŽIVI ZID, PROMIJENIMO HRVATSKU - PH, HRVATSKA SELJAČKA STRANKA - STJEPAN RADIĆ - HSS - SR, STRANKA IVANA PERNARA - SIP, HRVATSKA STRANKA SVIH ČAKAVACA KAJKAVACA I ŠTOKAVACA - HSSČKŠ, ZAGORSKA STRANKA ZA ZAGREB - ZSZ, NEZAVISNA LISTA STIPE PETRINA - NLSP": "ŽIVI ZID",
        '"BANDIĆ MILAN 365 - STRANKA RADA I SOLIDARNOSTI" - "365 STRANKA RADA I SOLIDARNOSTI"': "STRANKA RADA I SOLIDARNOSTI",
        "ŽELJKO LACKOVIĆ - NEZAVISNE LISTE, NARODNA STRANKA - REFORMISTI - REFORMISTI, HRVATSKA SELJAČKA STRANKA BRAĆE RADIĆ - HSS BRAĆE RADIĆ, NEZAVISNI SELJACI HRVATSKE - NSH, HRVATSKA DEMOKRŠĆANSKA STRANKA - HDS": "REFORMISTI",
        "HRVATSKA DEMOKRATSKA ZAJEDNICA - HDZ": "HDZ",
        "HRVATSKA NARODNA STRANKA - LIBERALNI DEMOKRATI - HNS": "HNS",
        "NARODNA STRANKA - REFORMISTI - REFORMISTI, HRVATSKA SELJAČKA STRANKA BRAĆE RADIĆ - HSS BRAĆE RADIĆ, STRANKA HRVATSKIH UMIROVLJENIKA - UMIROVLJENICI - UMIROVLJENICI": "REFORMISTI",
        "MOŽEMO! - POLITIČKA PLATFORMA, NOVA LJEVICA - NL, RADNIČKA FRONTA - RF, ODRŽIVI RAZVOJ HRVATSKE - ORAH, ZAGREB JE NAŠ!, ZA GRAD": "MOŽEMO!",
        "HRVATSKA NARODNA STRANKA - LIBERALNI DEMOKRATI - HNS, HRVATSKA SELJAČKA STRANKA BRAĆE RADIĆ - HSS BRAĆE RADIĆ": "HNS",
        "SNAGA SLAVONIJE I BARANJE - Snaga SiB": "Snaga SiB",
        "SOCIJALDEMOKRATSKA PARTIJA HRVATSKE - SDP, HRVATSKA SELJAČKA STRANKA - HSS, HRVATSKA STRANKA UMIROVLJENIKA - HSU, SNAGA - STRANKA NARODNOG I GRAĐANSKOG AKTIVIZMA - SNAGA, GRAĐANSKO-LIBERALNI SAVEZ - GLAS, ISTARSKI DEMOKRATSKI SABOR - IDS, PRIMORSKO GORANSKI SAVEZ - PGS, NARODNA STRANKA - REFORMISTI - REFORMISTI": "SDP",
        "SOCIJALDEMOKRATSKA PARTIJA HRVATSKE - SDP, ISTARSKI DEMOKRATSKI SABOR - IDS, PRIMORSKO GORANSKI SAVEZ - PGS, HRVATSKA SELJAČKA STRANKA - HSS, HRVATSKA STRANKA UMIROVLJENIKA - HSU, SNAGA - STRANKA NARODNOG I GRAĐANSKOG AKTIVIZMA - SNAGA, GRAĐANSKO-LIBERALNI SAVEZ - GLAS": "SDP",
        "MOŽEMO! - POLITIČKA PLATFORMA, RADNIČKA FRONTA - RF, NOVA LJEVICA - NL, ODRŽIVI RAZVOJ HRVATSKE - ORAH, ZAGREB JE NAŠ!, ZA GRAD": "MOŽEMO!",
        "DEMOKRATI, HRVATSKI LABURISTI - STRANKA RADA, LISTA ZA RIJEKU": "LABURISTI",
        "UNIJA KVARNERA - UNIJA": "UNIJA",
        "NEZAVISNA LISTA STIPE PETRINA - NLSP, AKCIJA MLADIH - AM, ŽIVI ZID, PROMIJENIMO HRVATSKU - PH, STRANKA IVANA PERNARA - SIP": "ŽIVI ZID",
        "NEOVISNI ZA HRVATSKU - NHR, HRVATSKA STRANKA PRAVA - HSP, GENERACIJA OBNOVE - GO": "HSP",
        "HRVATSKA DEMOKRATSKA ZAJEDNICA - HDZ, HRVATSKA DEMOKRŠĆANSKA STRANKA - HDS": "HDZ",
        "BRANITELJSKO DOMOLJUBNA STRANKA HRVATSKE - BDSH, HRVATSKA BRANITELJSKA PUČKA STRANKA - HBPS": "HBPS",
        "HRVATSKI DEMOKRATSKI SAVEZ SLAVONIJE I BARANJE - HDSSB": "HDSSB",
        "BRANITELJSKO DOMOLJUBNA STRANKA HRVATSKE - BDSH": "BDSH",
        "AUTOHTONA - HRVATSKA STRANKA PRAVA - A - HSP": "A-HSP",
        '"BANDIĆ MILAN 365 - STRANKA RADA I SOLIDARNOSTI", ISTARSKI DEMOKRATI - DEMOCRATICI ISTRIANI - ID - DI, DEMOKRATSKA PRIGORSKO - ZAGREBAČKA STRANKA - DPS, DEMOKRATSKA STRANKA ŽENA - DSŽ, HRVATSKA EUROPSKA STRANKA - HES, HRVATSKA RADNIČKA STRANKA - HRS, HRVATSKA STRANKA ZELENIH - EKO SAVEZ - ZELENI, MEĐIMURSKA STRANKA - MS, NEZAVISNI SELJACI HRVATSKE - NSH, NOVI VAL - STRANKA RAZVOJA - NOVI VAL, STRANKA UMIROVLJENIKA - SU, UMIROVLJENIČKA DEMOKRATSKA UNIJA - UDU, ZELENI SAVEZ - ZELENI, ZELENA STRANKA - ZS': "STRANKA RADA I SOLIDARNOSTI"
    }
}


def get_full_name(year, name):
    for p in parties_mapping[year]:
        if parties_mapping[year][p] == name:
            return p
    return name